### ISSUE TITLE
I am getting warnings when integrating the library in xCode 

### ISSUE THREAD

**Issue by shannoga** [iosdevzone/IDZPrecompiledVorbis#1]
Hi

Thanks a lot  for the library.
I am getting this warnings when integrating the library, am I doing something wrong ?

Thanks

```
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(analysis.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(bitrate.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(block.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(codebook.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(envelope.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(floor0.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(floor1.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(info.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(lookup.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(lpc.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(lsp.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(mapping0.o)
warning: ignoring debug info with an invalid version (0) in 

/Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(mdct.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(psy.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(registry.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(res0.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(sharedbook.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(smallft.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(synthesis.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(vorbisenc.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(vorbisfile.o)
warning: ignoring debug info with an invalid version (0) in /Volumes/ShanisDrive/WorkingCopies/SDKTest/apple/iToolbox/Media/Libs/iOS/Vorbis.framework/Vorbis(window.o)
```

**Comment by iosdevzone** [comment]
Hi there,

I have not seen these warnings before. Which version of Xcode are you using?

While I will try to figure out why this is happening, it is worth realizing that these are just warnings and should not alter the operation of the library.

Regards,
idz

**Comment by javierc** [comment]
Hello, I'm also getting those warnings. I'm using Xcode Version 6.1.1 (6A2008a). Thank you

**Comment by iosdevzone** [comment]
Hi @javierc, thanks for the additional information. I will check it out and get back to you. I think these warnings are just due to incompatibilities between different compiler versions and that they do not affect the functioning of the library. 
Apart from the warnings, is the library functioning correctly for you?
Regards,
Danny

**Comment by javierc** [comment]
Thank you @iosdevzone it is working properly on 64bit devices.. 

however, I'm getting a crash on the ipad 2 ios 6.1.3 at the point where IDZOggVorbisFileDecoder is going to read the buffer "nBytesRead = ov_read(&mOggVorbisFile,..." 

with the following message: 
dyld: lazy symbol binding failed: Symbol not found: ___sincos_stret
  Referenced from: /var/mobile/Applications/7CB9551D-7C06-409C-ABFC-1EAB87F2B897/test.app/test
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by iosdevzone** [comment]
Hi Javier, 
The problem you are running into is because the libraries are currently compiled with ios-simulator-version-min=7.0 and iphoneos-version-min=7.0.
You can work around this by recompiling them yourself with an lower minimum version. 
Luckily, using the scripts I provide this should not be too difficult (hopefully).
You can find instructions on how to reproduce the build in the README at  http://github.com/iosdevzone/IDZPrecompiledVorbis.
You will need to edit the `ids_build` script (part of the http://github.com/iosdevzone/IDZBuild repository) and change the occurrences of the above flags to the value you want. 
Let me know if you run into difficulties. 
Hope this helps, 
Danny @iOSDevZone

**Comment by javierc** [comment]
ah! yes. Thank you very much. I changed iphoneos-version-min to 6.0 and recompiled the libraries. However, I also had to update the values of IDZ_OGG_VERSION, IDZ_OGG_SDK_VERSION, IDZ_VORBIS_VERSION and IDZ_IOS_SDK_VERSION to the latest values (as of Feb.5th,2015 ogg is at 1.3.2, vorbis is at 1.3.4, and ios sdk is at 8.1). Cheers! great blog btw.

**Comment by iosdevzone** [comment]
Great! Sorry I could not do it for you. So busy here. 
Glad you like the blog. Don't get enough time to write on it. But it is very cool to know that people find it useful.
